Add license agreements for Dräger X-am 2800 - 5800
Draegerwerk/draegerwerk.github.io pull request #33
Opened 2022-05-09 13:16 UTC by efdece

2022-05-09 13:19 UTC, Hickstone requested changes

2022-05-09 13:19 UTC, Hickstone commented on products.json
> +                                        "a_attr": { "href": "assets/license_agreements/X-am-2800-5800/License%20Agreements.pdf" },
There is no whitespace (%20) in the file you uploaded.

2022-05-12 11:37 UTC, wackinger approved these changes

2022-05-12 11:49 UTC, nathanhi approved these changes

2022-05-12 11:50 UTC, merged