Safe track license agreements
Draegerwerk/draegerwerk.github.io pull request #6
Opened 2021-01-03 21:43 UTC by FMarquardtDraeger

License agreements for Dräger SafeTrack Application

2021-01-03 22:06 UTC, nathanhi requested changes
Some of these licenses require an additional acknowledgment (i.e. Apache License 1.1, CMU, OpenSSL, ..). Do you intend to add them to this page or are they located elsewhere (i.e. documentation)?

I assume this document was already approved by legal?

Are there any components that have been modified and need to be open sourced to comply with their license (i.e. GPL)? If so, please link them on this page as well - let us know if you need a new public repository in the @Draegerwerk organization!

2021-01-04 07:11 UTC, wackinger approved these changes

2021-01-11 09:57 UTC, FMarquardtDraeger commented on products.json
> +                               	"text": "Dräger SafeTrack",
Changed to use spaces.

2021-03-13 14:21 UTC, ptrsny requested changes

2021-03-13 14:21 UTC, ptrsny commented on products.json
> +                               	"text": "Dräger SafeTrack",
The indentation level itself is not correct. Pls fix that.

2021-03-15 07:22 UTC, closed without merging