Restructure product tree.
Draegerwerk/draegerwerk.github.io pull request #74
Opened 2023-03-06 14:13 UTC by efdece

* Add M540 Converter Service license agreements.

2023-03-06 14:36 UTC, wackinger approved these changes

2023-03-07 09:22 UTC, ptrsny requested changes
as mentioned in commends

2023-03-07 09:22 UTC, ptrsny commented on products.json
> +                          "href": "assets/licenses/Safety%20Products/Gas%20Detection/Mobile%20Gas%20Detection/X-am/X-am%202800%20\u2013%205800/License-Agreements.pdf"
\u2013 ?
urlencode suggests: %E2%80%93

2023-03-07 10:01 UTC, efdece commented on products.json
> +                          "href": "assets/licenses/thirdparty_notices/WindRiver/08b03cdb23a9366d8ab695631004167e95dc50b92642048bbc96dd3abb705649/legal-notices.zip"
Corrected

2023-03-07 11:01 UTC, ptrsny approved these changes

2023-03-07 13:58 UTC, nathanhi approved these changes

2023-03-07 13:58 UTC, merged